name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master   # oder main, je nach Branch-Name!

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v5
      - uses: actions/jekyll-build-pages@v1
      - uses: actions/upload-pages-artifact@v3
      - uses: actions/deploy-pages@v4
